name: Amalgamate Ubuntu 24.04 CI

on: [push, pull_request]

jobs:
  ubuntu-build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.1
      - name: Compile with amalgamation
        run: |
          mkdir build &&
          mkdir build/fast_float &&
          python3 ./script/amalgamate.py > build/fast_float/fast_float.h &&
          cp tests/string_test.cpp build/ &&
          cd build &&
          g++ string_test.cpp
