name: Publish to BCR

on:
  release:
    types: [published]

  # Allow manual triggering from GH UI
  workflow_dispatch:
    inputs:
      registry_fork:
        required: true
        description: The Bazel registry fork to push to when opening up a pull request"
        type: string
      tag_name:
        description: 'Tag name to publish (e.g., v1.2.3)'
        required: true
        type: string

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  publish:
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v1.1.0
    with:
      tag_name: ${{ github.event.release.tag_name || inputs.tag_name }}
      registry_fork: ${{ inputs.registry_fork }}
      attest: true
    secrets:
      publish_token: ${{ secrets.BCR_PUBLISH_TOKEN }}
