name: Ubuntu 22.04 CI (clang 14)

on: [push, pull_request]

jobs:
  ubuntu-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install clang++-14
        run: sudo apt-get install -y clang++-14
      - name: Use cmake
        run: |
          mkdir build &&
          cd build &&
          CXX=clang++-14 cmake -DFASTFLOAT_TEST=ON  ..  &&
          cmake --build .   &&
          ctest --output-on-failure
      - name: Use cmake CXX20
        run: |
          mkdir build20 &&
          cd build20 &&
          CXX=clang++-14 cmake -DFASTFLOAT_CONSTEXPR_TESTS=ON -DCMAKE_CXX_STANDARD=20 -DFASTFLOAT_TEST=ON  ..  &&
          cmake --build .   &&
          ctest --output-on-failure 