name: Ubuntu 24.04 CI (GCC 13)

on: [push, pull_request]

jobs:
  ubuntu-build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Use cmake
        run: |
          set -xe
          cmake -B build \
             -DFASTFLOAT_TEST=ON \
             -DFASTFLOAT_BENCHMARKS=ON \
             -DCMAKE_CXX_FLAGS=' -Werror -Wundef '
          cmake --build build --parallel
          ( cd build ; ctest --output-on-failure )
      - name: Use cmake CXX23
        run: |
          set -xe
          cmake -B build20 \
             -DFASTFLOAT_TEST=ON \
             -DFASTFLOAT_CONSTEXPR_TESTS=ON \
             -DFASTFLOAT_FIXEDWIDTH_TESTS=ON \
             -DFASTFLOAT_CXX_STANDARD=23 \
             -DCMAKE_CXX_FLAGS=' -Werror -Wundef '
          cmake --build build20 --parallel
          ( cd build20 ; ctest --output-on-failure )
