name: VS16-Ninja-CI

on: [push, pull_request]

jobs:
  ci:
    name: windows-vs16
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Run CMake with VS16'
      uses: lukka/run-cmake@v2
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        buildDirectory: "${{ github.workspace }}/../../_temp/windows"
        cmakeBuildType: Release
        buildWithCMake: true
        cmakeGenerator: VS16Win64
        cmakeAppendedArgs:  -G Ninja  -DFASTFLOAT_TEST=ON
        buildWithCMakeArgs: --config Release  

    - name: 'Run CTest'
      run: ctest -C Release   --output-on-failure -R basictest
      working-directory: "${{ github.workspace }}/../../_temp/windows"